<?php

namespace DoctrineORMModule\Proxy\__CG__\Forum\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Forum extends \Forum\Entity\Forum implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'idForum', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'titreF', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'texteF', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'dateF', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'categorie', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'idCat', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'idCreateur', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'idParent'];
        }

        return ['__isInitialized__', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'idForum', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'titreF', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'texteF', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'dateF', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'categorie', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'idCat', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'idCreateur', '' . "\0" . 'Forum\\Entity\\Forum' . "\0" . 'idParent'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Forum $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdForum()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdForum();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdForum', []);

        return parent::getIdForum();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreF', []);

        return parent::getTitreF();
    }

    /**
     * {@inheritDoc}
     */
    public function getTexteF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTexteF', []);

        return parent::getTexteF();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateF', []);

        return parent::getDateF();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCat', []);

        return parent::getIdCat();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCreateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCreateur', []);

        return parent::getIdCreateur();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdParent', []);

        return parent::getIdParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdForum($idForum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdForum', [$idForum]);

        return parent::setIdForum($idForum);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreF($titreF)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreF', [$titreF]);

        return parent::setTitreF($titreF);
    }

    /**
     * {@inheritDoc}
     */
    public function setTexteF($texteF)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTexteF', [$texteF]);

        return parent::setTexteF($texteF);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateF(\DateTime $dateF)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateF', [$dateF]);

        return parent::setDateF($dateF);
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie($categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCat($idcat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCat', [$idcat]);

        return parent::setIdCat($idcat);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCreateur($idCreateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCreateur', [$idCreateur]);

        return parent::setIdCreateur($idCreateur);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdParent($idParent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdParent', [$idParent]);

        return parent::setIdParent($idParent);
    }

}
