<div><?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('projet'));
    $form->prepare();

    echo $this->form()->openTag($form);
    ?>

    <table>
        <tfoot>
            <tr>
                            <td>
                    <p>
                        <?php echo $this->formInput($form->get('idparent')); ?>
                    </p>
                    <?php echo $this->formElementErrors($form->get('idparent'), array('class' => 'error_list')); ?>
                </td>
            </tr>
            <tr>
      
                <td>
                    <p>
                        <?php echo $this->formInput($form->get('idp')); ?>
                    </p>
                    <?php echo $this->formElementErrors($form->get('idp'), array('class' => 'error_list')); ?>
                </td>
            </tr>
            <tr>
                <td >
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                </td>
            </tr>
        </tfoot>
        <tbody>

            <tr>
                <th><?php echo $this->formLabel($form->get('titre')); ?></th>
                <td>
                    <p>
                        <?php echo $this->formInput($form->get('titre')); ?>
                    </p>
                    <?php echo $this->formElementErrors($form->get('titre'), array('class' => 'error_list')); ?>
                </td>
            </tr>
            <tr>

                <td>
                    <p>
                        <?php echo $this->formRow($form->get('texte')); ?>
                    </p>
                    <?php echo $this->formElementErrors($form->get('texte'), array('class' => 'error_list')); ?>
                </td>
            </tr>
            </form>
            </div>