<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('FindMyCoop') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                               ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
                 

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/event.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

   </head>
    <body>

        <header>
            <img src="/../img/fmc.png" alt="Zend Framework 2"/>

        </header>
        <nav class="navbar navbar-inverse navbar-top" role="navigation">
            
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="<?php echo $this->url('projet') ?>"><?php echo $this->translate('Projets') ?></a></li>
                        <li><a href="<?php echo $this->url('membre') ?>"><?php echo $this->translate('Membres') ?></a></li>
                        <li><a href="<?php echo $this->url('bar') ?>"><?php echo $this->translate('Bar') ?></a></li>

                    
                    </ul>
                </div><!--/.nav-collapse -->
            
        </nav>
        <div class="container">
        <div class="col-md-9 corps">
            <?php echo $this->content; ?>
               </div> 
        <div id="event" class="event col-md-2">

            <?php            
                $nom = "Se connecter";          
            if($_SESSION){
                $nom = "Se Déconnecter";
            ?>
            <ul>
                <li><a href="/">Mes projets</a></li>
                <li><a href="/message">Mes messages</a></li>
                <li><a href="/setting">Mon profil</a></li>
                <?php if($_SESSION['admin']==1){
                    ?><li><a href="/admin">Admin</a></li><?php
            }}
            ?> <li><a href="/connect"><?php echo $nom; ?></a></li>
                <li><a href="/contact">Contact</a></li>
            
            </ul>
            <h3>Evènements:</h3>
            </div>
            <hr>
           <footer class="col-md-12">            
              
               <p>&COPY;  Tous droits réservés. Toute reproduction partielle ou totale est strictement interdite. </p>
           </footer>
     
        <?php echo $this->inlineScript() ?>
        </div>
         <script>
             $(document).ready(function() {
                           $.ajax({
        url: "/event",
        dataType: 'json',
  complete : function(event){
      
event=event.responseText  ;
console.log(event.length);
$('#event').append(event);


}
    });
                });
        </script>
    </body>
    
   
</html>