<script>
var toto =0;
    $(document).ready(function() {
    $('.cat').click(function() {
            $("#" + $(this).attr('id') + " ul").slideToggle("slow");
    });
  }); 
		$(document).ready(function() {
			$('#projet0').click(function() {
				$('#projets0').slideToggle("slow");
			});         
			$("#projet1").click(function() {
				$("#projets1").slideToggle("slow");
			});		
			$("#projet2").click(function() {
				$("#projets2").slideToggle("slow");
			});             
			$("#projet3").click(function() {
				$("#projets3").slideToggle("slow");
			});                 
			$("#projet4").click(function() {
				$("#projets4").slideToggle("slow");
			});                 
			$("#projet5").click(function() {
				$("#projets5").slideToggle("slow");
			});
		});

</script><div id="post">
<?php
if ($_SESSION) {
    ?> <a href="/creatb">Nouveau</a><br><br>
    <?php
    } ?> <ul> <?php
foreach ($bar as $key1 => $cat) :
    if (empty($cat->getIdParent())) {
        ?><li class="cat" id="projet<?php echo $key1 ?>" ><?php echo $cat->getNomCat(); ?> </li><ul class="ps" id="projets<?php echo $key1; ?>">
            <?php
        }
        foreach ($bar as $key => $cat1):
            if ($objet = $cat1->getIdParent()) {
                if ($objet->getIdCat() == $cat->getIdCat()) {
                    ?><li class="scat"><?php echo $cat1->getNomCat(); ?></li> <?php
                    foreach ($forum as $post):
                        if ($cat1->getIdCat() == $post->getIdCat()->getIdCat()) {
                            ?>  <a href="detailb/<?php echo $post->getIdForum(); ?>" ><article>
                                             <?php echo $post->getTitreF(); ?>  <?php
                            ?> <span> <?php echo ' Auteur : ';
                        echo $post->getIdCreateur()->getNom();
                            ?>  </span> </article></a><?php
                    }

                endforeach;
                    ?>  <?php
                    }
                }
            endforeach;
            ?>

        </ul>






            <?php endforeach; ?></ul></div>
