
<?php
  $form = $this->form;
      $form->prepare();
    $form->setAttribute('action', $this->url('contact'));
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
?>
<table>

    <theader>

        <h1>Contact :</h1>
    </theader>
    <tfoot>
        <tr>
            <td colspan="2">
<?php echo $this->formSubmit($form->get('submit')); ?>
            </td>
        </tr>
    </tfoot>
    <tbody>
    
    <tr>
        <th><?php echo $this->formLabel($form->get('dest')); ?>
        </th>
        <td>
            <p>
<?php echo $this->formInput($form->get('dest'))." "; ?>
Saisir "admin" pour contacter directement l'administrateur du site
            </p>    
<?php echo $this->formElementErrors($form->get('dest'), array('class' => 'error_list')); ?>
        </td>

    </tr>
    <tr>
        <th><?php echo $this->formLabel($form->get('sujet')); ?></th>
        <td>
            <p>
<?php echo $this->formInput($form->get('sujet')); ?>

            </p>
<?php echo $this->formElementErrors($form->get('sujet'), array('class' => 'error_list')); ?>
        </td>

    </tr>
    <tr>
        
      <td colspan="2" width="90%">
            <p>
<?php echo $this->formRow($form->get('text')); ?>

            </p>
<?php echo $this->formElementErrors($form->get('text'), array('class' => 'error_list')); ?>
        </td>

    </tr>
  

</tbody>
</table>
<?php
echo $this->form()->closeTag();
?>                   