<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user'));
$form->prepare();
echo $this->form()->openTag($form);
if ($set->getPhoto()) {
    $photo = "photo" . $set->getIdMembre();
} else {
    $photo = "defaut";
}
?>
<table>

    <theader>

        <h1>Modification :</h1>
        <h2>Profil : </h2>
    </theader>
    <tfoot>
        <tr>
            <td colspan="2">
<?php echo $this->formSubmit($form->get('submit')); ?>
            </td>
        </tr>
    </tfoot>
    <tbody>
    <td><img src="../../img/membre/<?php echo $photo; ?>.jpg" alt=""></td>
    <tr>
        <th><?php echo $this->formLabel($form->get('name')); ?>
        </th>
        <td>
            <p>
<?php echo $this->formInput($form->get('name')); ?>

            </p>    
<?php echo $this->formElementErrors($form->get('name'), array('class' => 'error_list')); ?>
        </td>

    </tr>
    <tr>
        <th><?php echo $this->formLabel($form->get('prenom')); ?></th>
        <td>
            <p>
<?php echo $this->formInput($form->get('prenom')); ?>

            </p>
<?php echo $this->formElementErrors($form->get('prenom'), array('class' => 'error_list')); ?>
        </td>

    </tr>
    <tr>
        <th><?php echo $this->formLabel($form->get('pseudo')); ?></th>
        <td>
            <p>
<?php echo $this->formInput($form->get('pseudo')); ?>
            </p>
                <?php echo $this->formElementErrors($form->get('pseudo'), array('class' => 'error_list')); ?>
            <a href="<?php echo password; ?>">Changer mot de passe</a>
        </td>

    </tr>

    <tr>
        <th><?php echo $this->formLabel($form->get('adresse')); ?></th>
        <td>
            <p>
<?php echo $this->formInput($form->get('adresse')); ?>
            </p>
                <?php echo $this->formElementErrors($form->get('adresse'), array('class' => 'error_list')); ?>
        </td>

    </tr>
    <tr>
        <th><?php echo $this->formLabel($form->get('email')); ?></th>
        <td>
            <p>
<?php echo $this->formInput($form->get('email')); ?>
            </p>
                <?php echo $this->formElementErrors($form->get('email'), array('class' => 'error_list')); ?>
        </td>

    </tr>
    <tr>
        <th><?php echo $this->formLabel($form->get('ville')); ?></th>
        <td>
            <p>
<?php echo $this->formSelect($form->get('ville')); ?>
            </p>

<?php echo $this->formElementErrors($form->get('ville'), array('class' => 'error_list')); ?>
            <a href="http://<?php echo $set->getSiteweb()?>"> Site Web </a>
                             
        </td>
    </tr>

</tbody>
</table>
<?php
echo $this->form()->closeTag();
?>                   